export PARALLEL_BUILD = 3
export BUILD_SCRIPT = $(PWD)/submodules/ruckus/system_build_all.mk
export SETUP_ENV    = $(PWD)/setup_env.csh
export TARGET_DIRS  = $(PWD)/targets/EvrCardG2/

# Use top level makefile
include $(BUILD_SCRIPT)
