# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K70TFBG676-1

export COMMON_FILE = 

export REMOVE_UNUSED_CODE = 1

export TIMING_EXT_PKG = 1

# Define TOP directory
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include ../shared_version.mk
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
